platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def pods
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.6'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'MJExtension', '~> 3.0.10'
    pod 'NJKWebViewProgress', '~> 0.2.3'
    pod 'MJRefresh', '~> 3.1.0'
end

target 'BSBDJ'  do
    pods

end